"""
Messages contain:
role: Identifies the message type(system/user)
content: represents the actual content of the message ( test, images, audio, documents etc)
metadata: optional fields such as response info,  message ids and token usage

types of promots: text prompts and message prompts
Text Promt: simple string, staright forward promts, use when there's no need to retain the message history
Message Prompts: list of messages, use when there's need to retain the message history

messsage types:
1) system message: tells the model how to behave and proves content for interactions
2) human message: represents user input and interactions with the model
3) AI message: responses generated by the model, includeing text content, tool call and meta data
4) tool message: represents the output of the tool calls
"""

from langchain.messages import SystemMessage, HumanMessage, AIMessage
from langchain.chat_models import init_chat_model
from langchain.messages import AIMessage, ToolMessage
from dotenv import load_dotenv
import os

load_dotenv()
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

model = init_chat_model(model="gpt-4.1", temperature=0)

messages = [
    SystemMessage("You are a poetry expert"),
    HumanMessage("Write a poem on artificial intelligence")
]

response = model.invoke(messages)
print(response.content) 

ai_message = AIMessage(
    content = [],
    tool_calls=[
        {
            "name":"get_weather",
            "args":{
                "city":"karachi"
            }  ,
            "id":"call_123"
        }
    ]
)

weather_result = "Sunny, 72 degree Farhenheit"
tool_message = ToolMessage(
    content = weather_result,
    tool_call_id = "call_123"
)

messages.append(ai_message)
messages.append(tool_message)
final_response = model.invoke(messages)
print(final_response.content)